### ISSUE TITLE
Key to reveal client IP's and secrets is hard-coded and publicly visible.

### ISSUE THREAD

**Issue by DevEthan** [alphagov/govwifi#19]
In src/clients/index.php, the key value needed to run the script and reveal client IP's and secrets is hard coded and publically visible. This means that anyone could find this key and use this restricted service.

I'm sending a pull request for a temporary solution that hashes the key and only stores that in the script, but in any case the key should most likely be changed since it's now been revealed publically.

https://github.com/alphagov/govwifi/pull/20

**Comment by DevEthan** [comment]
https://github.com/alphagov/govwifi/pull/20

**Comment by afoldesi-gds** [comment]
Hi there, it's much appreciated, however I have a change going in for this already - just started with the other side - the build file changes necessary. 
The idea is that this value is pushed from the environment-specific terraform script. The final step to that will be the change here to use the environment variable.

**Comment by afoldesi-gds** [comment]
Oh, just to clarify, some of our build env is in a private repo for now - I'm hoping to publish the terraform scripts - and, well, everything I can - right here in the upcoming weeks.

**Comment by DevEthan** [comment]
Hi, thanks for the explanation, since your already on top of this I'll close my pull request.

**Comment by afoldesi-gds** [comment]
Ah thanks, and keep watch if you're interested in the project, there are quite a few changes lined up before the year is out.

**Comment by AlistairHCowan** [comment]
Closing as there is already a fix in the pipeline. Access lists lower the priority of this issue.
