### ISSUE TITLE
Please add a readme

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govwifi#76]
It would be helpful if this project had a readme so people know what it is and how to run the code.

**Comment by 1DC** [comment]
I agree. I've been contributing and still have no idea what this is for.

**Comment by afoldesi-gds** [comment]
:) it's coming! In the meantime: https://www.gov.uk/government/publications/govwifi/govwifi

**Comment by 1DC** [comment]
Makes sense. Interesting project!

**Comment by edwardhorsford** [comment]
Is there any update to this?

If this really is the cross government solution to wifi, it would be really nice if such a high profile project had a readme describing what it is.

How does this project relate to #alphagov/user.wifi ?

**Comment by afoldesi-gds** [comment]
This is on the task list for the current sprint,
Yes.:) 
user.wifi was the prototype / alpha version of the project. Created this repo when I took it over and we decided on the name change.

**Comment by edwardhorsford** [comment]
Thanks for the update :)

If user.wifi is no longer in active development, can I suggest it be archived to https://github.com/gds-attic ? With a clear message at the top saying the status.

It's not clear to people viewing these two repos who or why they differ, or which one to look at.

**Comment by edwardhorsford** [comment]
@philandstuff has archived the other project. So now we just need a readme on this one. :)

**Comment by afoldesi-gds** [comment]
#85 Fixes this.
